version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1


workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          # Compare files on head of this branch
          base-revision: main
          # Config for continuation; herein we reuse this config itself
          config-path: .circleci/continue_config.yml
          # 3-column space-separated table for mapping; `path-to-test parameter-to-set value-for-parameter` for each row
          mapping: |
            module-a/.* run-module-a true
            module-b/.* run-module-b true
